# Generated by Django 4.0 on 2021-12-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP Address')),
                ('port', models.IntegerField(verbose_name='Port Number')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('status', models.IntegerField(verbose_name='Status')),
            ],
        ),
    ]
