# Generated by Django 3.0.8 on 2020-07-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP Address')),
                ('port', models.IntegerField(verbose_name='Port Number')),
            ],
        ),
        migrations.CreateModel(
            name='SecDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devman.Device')),
                ('status', models.BooleanField(default=False)),
            ],
            bases=('devman.device',),
        ),
        migrations.CreateModel(
            name='WeatherDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='devman.Device')),
                ('humidity', models.FloatField()),
                ('weather', models.FloatField()),
            ],
            bases=('devman.device',),
        ),
        migrations.CreateModel(
            name='SecAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devman.SecDevice', verbose_name='Device')),
            ],
        ),
    ]
