# Generated by Django 3.0.8 on 2020-07-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(max_length=15, verbose_name='IP Address')),
                ('port', models.IntegerField(verbose_name='Port Number')),
            ],
        ),
        migrations.CreateModel(
            name='SecAlarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devman.SecDevice', verbose_name='Device')),
            ],
        ),
    ]
