# Generated by Django 3.0.8 on 2020-07-23 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdevice',
            old_name='weather',
            new_name='temperature',
        ),
    ]
