# Generated by Django 3.0.8 on 2020-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secdevice',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP Address'),
        ),
    ]
