# Generated by Django 3.0.8 on 2020-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devman', '0002_auto_20200723_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='secdevice',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
